/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-08-30 03:54:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.staffs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class form_jsp extends org.apache.jasper.runtime.HttpJspBase
        implements org.apache.jasper.runtime.JspSourceDependent,
        org.apache.jasper.runtime.JspSourceImports {

    private static final javax.servlet.jsp.JspFactory _jspxFactory =
            javax.servlet.jsp.JspFactory.getDefaultFactory();

    private static java.util.Map<java.lang.String, java.lang.Long> _jspx_dependants;

    private static final java.util.Set<java.lang.String> _jspx_imports_packages;

    private static final java.util.Set<java.lang.String> _jspx_imports_classes;

    static {
        _jspx_imports_packages = new java.util.HashSet<>();
        _jspx_imports_packages.add("javax.servlet");
        _jspx_imports_packages.add("javax.servlet.http");
        _jspx_imports_packages.add("javax.servlet.jsp");
        _jspx_imports_classes = null;
    }

    private volatile javax.el.ExpressionFactory _el_expressionfactory;
    private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

    public java.util.Map<java.lang.String, java.lang.Long> getDependants() {
        return _jspx_dependants;
    }

    public java.util.Set<java.lang.String> getPackageImports() {
        return _jspx_imports_packages;
    }

    public java.util.Set<java.lang.String> getClassImports() {
        return _jspx_imports_classes;
    }

    public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
        if (_el_expressionfactory == null) {
            synchronized (this) {
                if (_el_expressionfactory == null) {
                    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
                }
            }
        }
        return _el_expressionfactory;
    }

    public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
        if (_jsp_instancemanager == null) {
            synchronized (this) {
                if (_jsp_instancemanager == null) {
                    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
                }
            }
        }
        return _jsp_instancemanager;
    }

    public void _jspInit() {
    }

    public void _jspDestroy() {
    }

    public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
            throws java.io.IOException, javax.servlet.ServletException {

        if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
            final java.lang.String _jspx_method = request.getMethod();
            if ("OPTIONS".equals(_jspx_method)) {
                response.setHeader("Allow", "GET, HEAD, POST, OPTIONS");
                return;
            }
            if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
                response.setHeader("Allow", "GET, HEAD, POST, OPTIONS");
                response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
                return;
            }
        }

        final javax.servlet.jsp.PageContext pageContext;
        javax.servlet.http.HttpSession session = null;
        final javax.servlet.ServletContext application;
        final javax.servlet.ServletConfig config;
        javax.servlet.jsp.JspWriter out = null;
        final java.lang.Object page = this;
        javax.servlet.jsp.JspWriter _jspx_out = null;
        javax.servlet.jsp.PageContext _jspx_page_context = null;


        try {
            response.setContentType("text/html");
            pageContext = _jspxFactory.getPageContext(this, request, response,
                    null, true, 8192, true);
            _jspx_page_context = pageContext;
            application = pageContext.getServletContext();
            config = pageContext.getServletConfig();
            session = pageContext.getSession();
            out = pageContext.getOut();
            _jspx_out = out;

            out.write("<!doctype html>\r\n");
            out.write("<html lang=\"en\">\r\n");
            out.write("<head>\r\n");
            out.write("<!-- Required meta tags -->\r\n");
            out.write("<meta charset=\"utf-8\">\r\n");
            out.write("<meta name=\"viewport\"\r\n");
            out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
            out.write("\r\n");
            out.write("<!-- Bootstrap CSS -->\r\n");
            out.write("<link rel=\"stylesheet\"\r\n");
            out.write("	href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\"\r\n");
            out.write("	integrity=\"sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO\"\r\n");
            out.write("	crossorigin=\"anonymous\">\r\n");
            out.write("\r\n");
            out.write("<title>Hello, world!</title>\r\n");
            out.write("</head>\r\n");
            out.write("<body>\r\n");
            out.write("	<main class=\"container\">\r\n");
            out.write("		<header class=\"row\">\r\n");
            out.write("			<div class=\"col\">\r\n");
            out.write("				<div class=\"alert alert-succes\">\r\n");
            out.write("					<h1>Dang Ky</h1>\r\n");
            out.write("				</div>\r\n");
            out.write("\r\n");
            out.write("			</div>\r\n");
            out.write("		</header>\r\n");
            out.write("		<section class=\"row\">\r\n");
            out.write("			<div class=\"col-7\">\r\n");
            out.write("				<div class=\"row\">\r\n");
            out.write("					<div class=\"col\">\r\n");
            out.write("						<form action=\"RegisterServlet\" method=\"post\"\r\n");
            out.write("							enctype=\"multipart/form-data\">\r\n");
            out.write("							<div class=\"form-group\">\r\n");
            out.write("								<label for=\"username\">Username</label> <input type=\"text\"\r\n");
            out.write("									id=\"username\" name=\"username\" class=\"form-control\">\r\n");
            out.write("							</div>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("							<div class=\"form-group\">\r\n");
            out.write("								<label for=\"pass\">Password</label> <input type=\"password\"\r\n");
            out.write("									id=\"pass\" name=\"password\" class=\"form-control\">\r\n");
            out.write("							</div>\r\n");
            out.write("\r\n");
            out.write("							<div class=\"form-group\">\r\n");
            out.write("								<label for=\"dateOfBirth\">Ngay Sinh</label> <input type=\"date\"\r\n");
            out.write("									id=\"dateOfBirth\" name=\"dateOfBirth\" class=\"form-control\">\r\n");
            out.write("							</div>\r\n");
            out.write("\r\n");
            out.write("							<div class=\"custom-file mb-4\">\r\n");
            out.write("								<label for=\"image\" class=\"custom-file-label\">Hinh</label> <input\r\n");
            out.write("									type=\"file\" id=\"image\" name=\"imageName\" name=\"dateOfBirth\"\r\n");
            out.write("									class=\"custom-file-input\">\r\n");
            out.write("							</div>\r\n");
            out.write("\r\n");
            out.write("							<div class=\"form-group\">\r\n");
            out.write("								<label for=\"gender\">GioiTinh</label>\r\n");
            out.write("								<div class=\"form-check form-check-inline\">\r\n");
            out.write("									<input type=\"radio\" class=\"form-check-input\" id=\"genderM\"\r\n");
            out.write("										name=\"gender\" value=\"true\" /> <label for=\"genderM\">Male</label>\r\n");
            out.write("								</div>\r\n");
            out.write("\r\n");
            out.write("								<div class=\"form-check form-check-inline\">\r\n");
            out.write("									<input type=\"radio\" class=\"form-check-input\" id=\"gendeFr\"\r\n");
            out.write("										name=\"gender\" value=\"false\" /> <label for=\"genderF\">Female</label>\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("\r\n");
            out.write("							<div class=\"form-group\">\r\n");
            out.write("								<div class=\"form-check\">\r\n");
            out.write("\r\n");
            out.write("									<input type=\"checkbox\" class=\"form-check-input\" name=\"married\"\r\n");
            out.write("										value=\"true\" /> <label for=\"married\">Da co gia dinh\r\n");
            out.write("										chua</label>\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("\r\n");
            out.write("							<div class=\"form-group\">\r\n");
            out.write("								<label for=\"nationality\">Quoc tich</label> <select\r\n");
            out.write("									name=\"nationality\" class=\"form-control\">\r\n");
            out.write("									<option>Viet Nam</option>\r\n");
            out.write("									<option>My</option>\r\n");
            out.write("									<option>Nhat</option>\r\n");
            out.write("								</select>\r\n");
            out.write("							</div>\r\n");
            out.write("\r\n");
            out.write("							<div class=\"form-group\">\r\n");
            out.write("								<label for=\"favorites\">So Thich</label>\r\n");
            out.write("								<div class=\"form-check form-check-inline\">\r\n");
            out.write("									<input type=\"checkbox\" class=\"form-check-input\"\r\n");
            out.write("										name=\"favorites\" id=\"read\" value=\"read\" /> <label for=\"red\">Doc\r\n");
            out.write("										Sach</label>\r\n");
            out.write("								</div>\r\n");
            out.write("\r\n");
            out.write("								<div class=\"form-check form-check-inline\">\r\n");
            out.write("									<input type=\"checkbox\" class=\"form-check-input\"\r\n");
            out.write("										name=\"favorites\" id=\"music\" value=\"music\" /> <label\r\n");
            out.write("										for=\"music\">Am nhac</label>\r\n");
            out.write("								</div>\r\n");
            out.write("\r\n");
            out.write("								<div class=\"form-check form-check-inline\">\r\n");
            out.write("									<input type=\"checkbox\" class=\"form-check-input\"\r\n");
            out.write("										name=\"favorites\" id=\"tourist\" value=\"tourist\" /> <label\r\n");
            out.write("										for=\"tourist\">Du lich</label>\r\n");
            out.write("								</div>\r\n");
            out.write("\r\n");
            out.write("								<div class=\"form-check form-check-inline\">\r\n");
            out.write("									<input type=\"checkbox\" class=\"form-check-input\"\r\n");
            out.write("										name=\"favorites\" id=\"orthers\" value=\"orthers\" /> <label\r\n");
            out.write("										for=\"orthers\">Khac</label>\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("\r\n");
            out.write("							<div class=\"form-group\">\r\n");
            out.write("								<label for=\"note\">Ghi Chu: </label>\r\n");
            out.write("								<textarea rows=\"3\" cols=\"\" name=\"note\" class=\"form-control\"></textarea>\r\n");
            out.write("							</div>\r\n");
            out.write("\r\n");
            out.write("							<hr>\r\n");
            out.write("\r\n");
            out.write("							<button type=\"submit\" class=\"btn btn-primary\">Dang Ky</button>\r\n");
            out.write("\r\n");
            out.write("						</form>\r\n");
            out.write("					</div>\r\n");
            out.write("				</div>\r\n");
            out.write("			</div>\r\n");
            out.write("\r\n");
            out.write("			<div class=\"col-5\">\r\n");
            out.write("				<h3>Thong Tin Dang Dang Ky</h3>\r\n");
            out.write("				<ul>\r\n");
            out.write("\r\n");
            out.write("					<li><img alt=\"\" src=\"images/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${staff.imageName}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("\"\r\n");
            out.write("						class=\"img-fluid\" width=\"150\"></li>\r\n");
            out.write("					<li>Ten Dang Nhap: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${staff.username}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("					<li>NgaySinh: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${staff.dateOfBirth}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("					<li>Mat Khau: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${staff.password}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("					<li>gioitinh: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${staff.gender ? 'Nam' : 'Nu'}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("					<li>Lap gia dinh ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${staff.married ? 'Da Lap Gia Dinh' : 'Chua Lap Gia Dinh'}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("					<li>QUoc tich: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${staff.nationality}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("					<li>So Thich: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${staff.favorites}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("					<li>Ghi Chu: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${staff.note}", java.lang.String.class, (javax.servlet.jsp.PageContext) _jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("				</ul>\r\n");
            out.write("			</div>\r\n");
            out.write("		</section>\r\n");
            out.write("	</main>\r\n");
            out.write("	<!-- Optional JavaScript -->\r\n");
            out.write("	<!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n");
            out.write("	<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"\r\n");
            out.write("		integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\"\r\n");
            out.write("		crossorigin=\"anonymous\"></script>\r\n");
            out.write("	<script\r\n");
            out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"\r\n");
            out.write("		integrity=\"sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\"\r\n");
            out.write("		crossorigin=\"anonymous\"></script>\r\n");
            out.write("	<script\r\n");
            out.write("		src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\"\r\n");
            out.write("		integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\"\r\n");
            out.write("		crossorigin=\"anonymous\"></script>\r\n");
            out.write("</body>\r\n");
            out.write("</html>");
        } catch (java.lang.Throwable t) {
            if (!(t instanceof javax.servlet.jsp.SkipPageException)) {
                out = _jspx_out;
                if (out != null && out.getBufferSize() != 0)
                    try {
                        if (response.isCommitted()) {
                            out.flush();
                        } else {
                            out.clearBuffer();
                        }
                    } catch (java.io.IOException e) {
                    }
                if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
                else throw new ServletException(t);
            }
        } finally {
            _jspxFactory.releasePageContext(_jspx_page_context);
        }
    }
}
